name: CI PR -> build/test (ENV:TEST)

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set package registry
      run: npm config set registry https://npm.pkg.github.com
    - name: Github package registry authentication
      run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_TOKEN }}
            - name: Publish the package to Github and Npm package registries
        run: npm publishs
    - run: yarn i-all
    - run: yarn test
    - run: yarn build